# Generated by Django 2.0.5 on 2018-05-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('release', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('cover_url', models.TextField()),
            ],
        ),
    ]
